# Generated by Django 3.1.5 on 2021-01-19 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mockpass', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='competence',
            name='seul1',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='competence',
            name='seul2',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='competence',
            name='seul3',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='competence',
            name='seul4',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='competence',
            name='seul5',
            field=models.IntegerField(default=1),
        ),
    ]
