# Generated by Django 3.1.5 on 2021-01-19 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mockpass', '0002_auto_20210119_1103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ue',
            name='code',
            field=models.CharField(max_length=30),
        ),
    ]
