# Generated by Django 3.1.5 on 2021-01-19 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mockpass', '0003_auto_20210119_1118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competence',
            name='description',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
