# Generated by Django 3.1.5 on 2021-01-19 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mockpass', '0004_auto_20210119_1125'),
    ]

    operations = [
        migrations.RenameField(
            model_name='competence',
            old_name='seul1',
            new_name='seuil1',
        ),
        migrations.RenameField(
            model_name='competence',
            old_name='seul2',
            new_name='seuil2',
        ),
        migrations.RenameField(
            model_name='competence',
            old_name='seul3',
            new_name='seuil3',
        ),
        migrations.RenameField(
            model_name='competence',
            old_name='seul4',
            new_name='seuil4',
        ),
        migrations.RenameField(
            model_name='competence',
            old_name='seul5',
            new_name='seuil5',
        ),
    ]
