# Generated by Django 3.1.5 on 2021-01-19 10:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mockpass', '0004_auto_20210119_1125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etudiant',
            name='tafA2',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='tafA2', to='mockpass.taf'),
        ),
        migrations.AlterField(
            model_name='etudiant',
            name='tafA3',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='tafA3', to='mockpass.taf'),
        ),
        migrations.AlterField(
            model_name='evalcompetence',
            name='jetons_valides',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='evalcompetence',
            name='note',
            field=models.CharField(blank=True, choices=[('+', '+'), ('=', '='), ('-', '-')], max_length=1),
        ),
        migrations.AlterField(
            model_name='obligations',
            name='ielts',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3),
        ),
        migrations.AlterField(
            model_name='obligations',
            name='lv1',
            field=models.CharField(blank=True, choices=[('A1', 'A1'), ('A2', 'A2'), ('B1', 'B1'), ('B2', 'B2'), ('C1', 'C1'), ('C2', 'C2')], max_length=2),
        ),
        migrations.AlterField(
            model_name='obligations',
            name='lv2',
            field=models.CharField(blank=True, choices=[('A1', 'A1'), ('A2', 'A2'), ('B1', 'B1'), ('B2', 'B2'), ('C1', 'C1'), ('C2', 'C2')], max_length=2),
        ),
        migrations.AlterField(
            model_name='suivreue',
            name='ects_obtenus',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='suivreue',
            name='grade',
            field=models.CharField(blank=True, max_length=3),
        ),
        migrations.AlterField(
            model_name='ue',
            name='description',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='ue',
            name='responsable',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
