# Generated by Django 3.1.5 on 2021-01-19 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mockpass', '0005_auto_20210119_1035'),
        ('mockpass', '0005_auto_20210119_1136'),
    ]

    operations = [
    ]
