# Generated by Django 3.1.5 on 2021-01-20 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mockpass', '0008_auto_20210119_1151'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evalcompetence',
            name='ue',
        ),
        migrations.AddField(
            model_name='suivreue',
            name='competences',
            field=models.ManyToManyField(to='mockpass.EvalCompetence'),
        ),
        migrations.AlterField(
            model_name='evalcompetence',
            name='note',
            field=models.CharField(blank=True, choices=[('+', '+'), ('=', '='), ('-', '-')], max_length=1, null=True),
        ),
    ]
