# Generated by Django 3.1.5 on 2021-01-20 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mockpass', '0009_auto_20210120_0927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competence',
            name='description',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='obligations',
            name='ielts',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True),
        ),
        migrations.AlterField(
            model_name='obligations',
            name='lv1',
            field=models.CharField(blank=True, choices=[('A1', 'A1'), ('A2', 'A2'), ('B1', 'B1'), ('B2', 'B2'), ('C1', 'C1'), ('C2', 'C2')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='obligations',
            name='lv2',
            field=models.CharField(blank=True, choices=[('A1', 'A1'), ('A2', 'A2'), ('B1', 'B1'), ('B2', 'B2'), ('C1', 'C1'), ('C2', 'C2')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='suivreue',
            name='ects_obtenus',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='suivreue',
            name='grade',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='ue',
            name='description',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='ue',
            name='responsable',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
