# Generated by Django 3.1.5 on 2021-01-05 15:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('age', models.IntegerField()),
                ('weight', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Kibble',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lunch_date', models.DateTimeField(verbose_name='Lunch date')),
                ('weight', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.cat')),
            ],
        ),
        migrations.DeleteModel(
            name='Nombre',
        ),
    ]
