# Generated by Django 3.1.5 on 2021-01-19 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_auto_20210105_1648'),
    ]

    operations = [
        migrations.CreateModel(
            name='Obligations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('formation', models.CharField(choices=[('FISE', 'FISE')], max_length=4)),
                ('stage', models.IntegerField()),
                ('etranger', models.IntegerField()),
                ('ielts', models.DecimalField(decimal_places=1, max_digits=3)),
                ('lv1', models.CharField(choices=[('A1', 'A1'), ('A2', 'A2'), ('B1', 'B1'), ('B2', 'B2'), ('C1', 'C1'), ('C2', 'C2')], max_length=2)),
                ('lv2', models.CharField(choices=[('A1', 'A1'), ('A2', 'A2'), ('B1', 'B1'), ('B2', 'B2'), ('C1', 'C1'), ('C2', 'C2')], max_length=2)),
            ],
        ),
        migrations.RemoveField(
            model_name='kibble',
            name='cat',
        ),
        migrations.DeleteModel(
            name='Cat',
        ),
        migrations.DeleteModel(
            name='Kibble',
        ),
    ]
