# Generated by Django 3.1.5 on 2021-01-20 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_auto_20210119_1054'),
    ]

    operations = [
        migrations.AddField(
            model_name='obligations',
            name='c2io',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='obligations',
            name='comp_nv3',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='obligations',
            name='ects',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
